#!/bin/bash

WORKER_COUNT=$(oc get nodes -l node-role.kubernetes.io/worker --no-headers | wc -l)

if [ "$WORKER_COUNT" -eq 0 ]; then
  echo "No worker nodes available! Scaling up new nodes..."
  
  # Increase worker node count using OpenShift MachineSet
  oc scale machineset -n openshift-machine-api --replicas=3 $(oc get machineset -n openshift-machine-api -o jsonpath='{.items[0].metadata.name}')
  
  echo "New worker nodes are being provisioned."
else
  echo "Worker nodes are available."
fi
